# Generated by Django 3.2.9 on 2022-02-19 06:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
    ]
