# Generated by Django 3.2.9 on 2022-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0006_auto_20220414_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='areaofinterest',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='education',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='publications',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='research',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='subjects',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
