# Generated by Django 3.2.9 on 2022-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0007_auto_20220414_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
