# Generated by Django 3.2.9 on 2022-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0008_facultyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
