# Generated by Django 3.2.9 on 2022-04-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0010_auto_20220414_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='user',
        ),
    ]
