# Generated by Django 3.2.9 on 2022-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0011_remove_facultyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='Faculty_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
