# Generated by Django 3.2.9 on 2022-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0012_facultyprofile_faculty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='Faculty_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_image'),
        ),
    ]
