# Generated by Django 3.2.9 on 2022-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0013_auto_20220414_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
