# Generated by Django 3.2.9 on 2022-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0016_alter_facultyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
