# Generated by Django 3.2.9 on 2022-04-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0017_facultyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='f_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='l_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
